/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_maze_data.py from the disassembly of the maze rooms. Do not edit.

#include "igor/igor.h"

namespace Igor {

#define MAZE_EXIT(code, x1, y1, x2, y2, dir) { code, kMazeActionExit, x1, y1, x2, y2, dir, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
#define MAZE_STAIRS_EXIT(code, x, dir) { code, kMazeActionStairsExit, 0, 0, 0, 0, dir, x, 0, 0, 0, 0, 0, 0, 0, 0 }
#define MAZE_EXIT_FIXED(code, x1, y1, x2, y2, location, state, objectState, objectStateValue) 	{ code, kMazeActionExitFixed, x1, y1, x2, y2, 0, 0, location, state, objectState, objectStateValue, 0, 0, 0, 0 }
#define MAZE_DIALOGUE(code, lines, count, start, shown) { code, kMazeActionDialogue, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, lines, count, start, shown }

// The maze is a grid of locations. For each one: the locations to the north, east, south and west (0: none)
// and the shape of the room that shows it (the part is 50 + shape).
const MazeNode IgorEngine::MAZE_NODES[108] = {
	{ { 0, 0, 0, 0 }, 0 }, // 0
	{ { 0, 2, 22, 0 }, 8 }, // 1
	{ { 0, 3, 0, 1 }, 9 }, // 2
	{ { 0, 4, 0, 2 }, 9 }, // 3
	{ { 0, 0, 25, 3 }, 10 }, // 4
	{ { 0, 0, 26, 0 }, 3 }, // 5
	{ { 0, 7, 27, 0 }, 8 }, // 6
	{ { 0, 0, 28, 6 }, 10 }, // 7
	{ { 0, 9, 0, 0 }, 2 }, // 8
	{ { 0, 0, 30, 8 }, 10 }, // 9
	{ { 0, 11, 0, 0 }, 2 }, // 10
	{ { 0, 0, 32, 10 }, 10 }, // 11
	{ { 0, 13, 33, 0 }, 8 }, // 12
	{ { 0, 14, 34, 12 }, 12 }, // 13
	{ { 0, 15, 0, 13 }, 9 }, // 14
	{ { 0, 16, 36, 14 }, 12 }, // 15
	{ { 0, 17, 0, 15 }, 9 }, // 16
	{ { 0, 0, 38, 16 }, 10 }, // 17
	{ { 0, 0, 39, 0 }, 3 }, // 18
	{ { 0, 20, 40, 0 }, 8 }, // 19
	{ { 0, 21, 41, 19 }, 12 }, // 20
	{ { 0, 0, 42, 20 }, 10 }, // 21
	{ { 1, 23, 43, 0 }, 11 }, // 22
	{ { 0, 24, 0, 22 }, 9 }, // 23
	{ { 0, 0, 0, 23 }, 4 }, // 24
	{ { 4, 26, 46, 0 }, 11 }, // 25
	{ { 5, 0, 47, 25 }, 13 }, // 26
	{ { 6, 28, 48, 0 }, 11 }, // 27
	{ { 7, 29, 49, 27 }, 15 }, // 28
	{ { 0, 30, 0, 28 }, 9 }, // 29
	{ { 9, 0, 51, 29 }, 13 }, // 30
	{ { 0, 32, 0, 0 }, 2 }, // 31
	{ { 11, 33, 0, 31 }, 14 }, // 32
	{ { 12, 0, 54, 32 }, 13 }, // 33
	{ { 13, 35, 55, 0 }, 11 }, // 34
	{ { 0, 0, 56, 34 }, 10 }, // 35
	{ { 15, 0, 57, 0 }, 6 }, // 36
	{ { 0, 38, 58, 0 }, 8 }, // 37
	{ { 17, 39, 59, 37 }, 15 }, // 38
	{ { 18, 0, 60, 38 }, 13 }, // 39
	{ { 19, 0, 61, 0 }, 6 }, // 40
	{ { 20, 0, 62, 0 }, 6 }, // 41
	{ { 21, 0, 63, 0 }, 6 }, // 42
	{ { 22, 44, 0, 0 }, 5 }, // 43
	{ { 0, 45, 0, 43 }, 9 }, // 44
	{ { 0, 0, 66, 44 }, 10 }, // 45
	{ { 25, 0, 67, 0 }, 6 }, // 46
	{ { 26, 0, 68, 0 }, 6 }, // 47
	{ { 27, 0, 69, 0 }, 6 }, // 48
	{ { 28, 0, 70, 0 }, 6 }, // 49
	{ { 0, 51, 0, 0 }, 2 }, // 50
	{ { 30, 0, 72, 50 }, 13 }, // 51
	{ { 0, 53, 73, 0 }, 8 }, // 52
	{ { 0, 0, 0, 52 }, 4 }, // 53
	{ { 33, 0, 75, 0 }, 6 }, // 54
	{ { 34, 0, 0, 0 }, 1 }, // 55
	{ { 35, 0, 0, 0 }, 1 }, // 56
	{ { 36, 0, 0, 0 }, 1 }, // 57
	{ { 37, 59, 79, 0 }, 11 }, // 58
	{ { 38, 0, 80, 58 }, 13 }, // 59
	{ { 39, 0, 81, 0 }, 6 }, // 60
	{ { 40, 0, 82, 0 }, 6 }, // 61
	{ { 41, 0, 83, 0 }, 6 }, // 62
	{ { 42, 0, 84, 0 }, 6 }, // 63
	{ { 0, 65, 85, 0 }, 8 }, // 64
	{ { 0, 66, 0, 64 }, 9 }, // 65
	{ { 45, 0, 87, 65 }, 13 }, // 66
	{ { 46, 68, 88, 0 }, 11 }, // 67
	{ { 47, 0, 89, 67 }, 13 }, // 68
	{ { 48, 0, 90, 0 }, 6 }, // 69
	{ { 49, 71, 91, 0 }, 11 }, // 70
	{ { 0, 72, 0, 70 }, 9 }, // 71
	{ { 51, 0, 0, 71 }, 7 }, // 72
	{ { 52, 74, 94, 0 }, 11 }, // 73
	{ { 0, 0, 0, 73 }, 4 }, // 74
	{ { 54, 76, 96, 0 }, 11 }, // 75
	{ { 0, 77, 97, 75 }, 12 }, // 76
	{ { 0, 0, 98, 76 }, 10 }, // 77
	{ { 0, 0, 99, 0 }, 3 }, // 78
	{ { 58, 0, 100, 0 }, 6 }, // 79
	{ { 59, 81, 101, 0 }, 11 }, // 80
	{ { 60, 0, 0, 80 }, 7 }, // 81
	{ { 61, 0, 103, 0 }, 6 }, // 82
	{ { 62, 0, 104, 0 }, 6 }, // 83
	{ { 63, 0, 105, 0 }, 6 }, // 84
	{ { 64, 86, 0, 107 }, 14 }, // 85
	{ { 0, 87, 0, 85 }, 9 }, // 86
	{ { 66, 0, 0, 86 }, 7 }, // 87
	{ { 67, 89, 0, 0 }, 5 }, // 88
	{ { 68, 90, 0, 88 }, 14 }, // 89
	{ { 69, 0, 0, 89 }, 7 }, // 90
	{ { 70, 92, 0, 0 }, 5 }, // 91
	{ { 0, 93, 0, 91 }, 9 }, // 92
	{ { 0, 94, 0, 92 }, 9 }, // 93
	{ { 73, 95, 0, 93 }, 14 }, // 94
	{ { 0, 96, 0, 94 }, 9 }, // 95
	{ { 75, 0, 0, 95 }, 7 }, // 96
	{ { 76, 98, 0, 0 }, 5 }, // 97
	{ { 77, 0, 0, 97 }, 7 }, // 98
	{ { 78, 100, 0, 0 }, 5 }, // 99
	{ { 79, 0, 0, 99 }, 7 }, // 100
	{ { 80, 102, 0, 0 }, 5 }, // 101
	{ { 0, 103, 0, 101 }, 9 }, // 102
	{ { 82, 0, 0, 102 }, 7 }, // 103
	{ { 83, 0, 0, 0 }, 1 }, // 104
	{ { 84, 0, 106, 0 }, 6 }, // 105
	{ { 0, 0, 0, 0 }, 16 }, // 106
	{ { 0, 0, 0, 0 }, 17 } // 107
};

// parts 51, 52, 53, 54
static const RoomDataOffsets kMazeOffsets0 = {
	{ 0, 0, 0, 0 },
	{ 0, 3 },
	{ 3, 119, 2855, 7, 83, 76 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

// parts 55, 56, 57, 58, 67
static const RoomDataOffsets kMazeOffsets1 = {
	{ 0, 0, 0, 0 },
	{ 1, 6 },
	{ 7, 143, 2879, 31, 107, 76 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

// parts 59, 60
static const RoomDataOffsets kMazeOffsets2 = {
	{ 0, 0, 0, 0 },
	{ 1, 6 },
	{ 7, 139, 3019, 31, 107, 80 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

// parts 61, 62, 63, 64, 66
static const RoomDataOffsets kMazeOffsets3 = {
	{ 0, 0, 0, 0 },
	{ 2, 9 },
	{ 11, 163, 3043, 55, 131, 80 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

// parts 65
static const RoomDataOffsets kMazeOffsets4 = {
	{ 0, 0, 0, 0 },
	{ 3, 12 },
	{ 15, 187, 3067, 79, 155, 80 },
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

static const MazeEntry kMaze51Entries[] = {
	{ 510, kMazeEntryWalk, 163, 92, kFacingPositionFront, 163, 110 },
};

static const MazeDialogueLine kMaze51Lines102[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze51Actions[] = {
	MAZE_EXIT(101, 163, 107, 163, 92, 0),
	MAZE_DIALOGUE(102, kMaze51Lines102, 1, 1, 1),
};

static const MazeEntry kMaze52Entries[] = {
	{ 521, kMazeEntryWalk, 298, 128, kFacingPositionLeft, 240, 128 },
};

static const MazeDialogueLine kMaze52Lines102[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze52Actions[] = {
	MAZE_EXIT(101, 248, 128, 298, 128, 1),
	MAZE_DIALOGUE(102, kMaze52Lines102, 1, 1, 1),
};

static const MazeEntry kMaze53Entries[] = {
	{ 532, kMazeEntryStairs, 150, 0, 0, 0, 0 },
};

static const MazeDialogueLine kMaze53Lines102[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze53Actions[] = {
	MAZE_STAIRS_EXIT(101, 150, 2),
	MAZE_DIALOGUE(102, kMaze53Lines102, 1, 1, 1),
};

static const MazeEntry kMaze54Entries[] = {
	{ 543, kMazeEntryWalk, 16, 109, kFacingPositionRight, 50, 109 },
};

static const MazeDialogueLine kMaze54Lines102[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze54Actions[] = {
	MAZE_EXIT(101, 50, 109, 16, 109, 3),
	MAZE_DIALOGUE(102, kMaze54Lines102, 1, 1, 1),
};

static const MazeEntry kMaze55Entries[] = {
	{ 550, kMazeEntryWalk, 154, 92, kFacingPositionFront, 154, 110 },
	{ 551, kMazeEntryWalk, 298, 128, kFacingPositionLeft, 240, 128 },
};

static const MazeDialogueLine kMaze55Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze55Actions[] = {
	MAZE_EXIT(101, 154, 106, 154, 92, 0),
	MAZE_EXIT(102, 248, 128, 298, 128, 1),
	MAZE_DIALOGUE(103, kMaze55Lines103, 1, 1, 1),
};

static const MazeEntry kMaze56Entries[] = {
	{ 560, kMazeEntryWalk, 154, 92, kFacingPositionFront, 154, 110 },
	{ 562, kMazeEntryStairs, 154, 0, 0, 0, 0 },
};

static const MazeDialogueLine kMaze56Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze56Actions[] = {
	MAZE_EXIT(101, 154, 106, 154, 92, 0),
	MAZE_STAIRS_EXIT(102, 154, 2),
	MAZE_DIALOGUE(103, kMaze56Lines103, 1, 1, 1),
};

static const MazeEntry kMaze57Entries[] = {
	{ 570, kMazeEntryWalk, 209, 80, kFacingPositionFront, 209, 104 },
	{ 573, kMazeEntryWalk, 16, 109, kFacingPositionRight, 60, 109 },
};

static const MazeDialogueLine kMaze57Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze57Actions[] = {
	MAZE_EXIT(101, 209, 94, 209, 80, 0),
	MAZE_EXIT(102, 50, 109, 16, 109, 3),
	MAZE_DIALOGUE(103, kMaze57Lines103, 1, 1, 1),
};

static const MazeEntry kMaze58Entries[] = {
	{ 581, kMazeEntryWalk, 298, 128, kFacingPositionLeft, 240, 128 },
	{ 582, kMazeEntryStairs, 160, 0, 0, 0, 0 },
};

static const MazeDialogueLine kMaze58Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze58Actions[] = {
	MAZE_EXIT(101, 248, 128, 298, 128, 1),
	MAZE_STAIRS_EXIT(102, 160, 2),
	MAZE_DIALOGUE(103, kMaze58Lines103, 1, 1, 1),
};

static const MazeEntry kMaze59Entries[] = {
	{ 591, kMazeEntryWalk, 313, 109, kFacingPositionLeft, 259, 109 },
	{ 593, kMazeEntryWalk, 16, 109, kFacingPositionRight, 60, 109 },
};

static const MazeDialogueLine kMaze59Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze59Actions[] = {
	MAZE_EXIT(101, 269, 109, 313, 109, 1),
	MAZE_EXIT(102, 50, 109, 16, 109, 3),
	MAZE_DIALOGUE(103, kMaze59Lines103, 1, 1, 1),
};

static const MazeEntry kMaze60Entries[] = {
	{ 602, kMazeEntryStairs, 160, 0, 0, 0, 0 },
	{ 603, kMazeEntryWalk, 16, 109, kFacingPositionRight, 60, 109 },
};

static const MazeDialogueLine kMaze60Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze60Actions[] = {
	MAZE_STAIRS_EXIT(101, 160, 2),
	MAZE_EXIT(102, 50, 109, 16, 109, 3),
	MAZE_DIALOGUE(103, kMaze60Lines103, 1, 1, 1),
};

static const MazeEntry kMaze61Entries[] = {
	{ 610, kMazeEntryWalk, 209, 80, kFacingPositionFront, 209, 104 },
	{ 611, kMazeEntryWalk, 313, 108, kFacingPositionLeft, 243, 108 },
	{ 612, kMazeEntryStairs, 160, 0, 0, 0, 0 },
};

static const MazeDialogueLine kMaze61Lines104[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze61Actions[] = {
	MAZE_EXIT(101, 209, 94, 209, 80, 0),
	MAZE_EXIT(102, 253, 108, 313, 108, 1),
	MAZE_STAIRS_EXIT(103, 160, 2),
	MAZE_DIALOGUE(104, kMaze61Lines104, 1, 1, 1),
};

static const MazeEntry kMaze62Entries[] = {
	{ 621, kMazeEntryWalk, 313, 109, kFacingPositionLeft, 259, 109 },
	{ 622, kMazeEntryStairs, 160, 0, 0, 0, 0 },
	{ 623, kMazeEntryWalk, 16, 109, kFacingPositionRight, 60, 109 },
};

static const MazeDialogueLine kMaze62Lines104[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze62Actions[] = {
	MAZE_EXIT(101, 269, 109, 313, 109, 1),
	MAZE_STAIRS_EXIT(102, 160, 2),
	MAZE_EXIT(103, 50, 109, 16, 109, 3),
	MAZE_DIALOGUE(104, kMaze62Lines104, 1, 1, 1),
};

static const MazeEntry kMaze63Entries[] = {
	{ 630, kMazeEntryWalk, 164, 92, kFacingPositionFront, 164, 110 },
	{ 632, kMazeEntryStairs, 164, 0, 0, 0, 0 },
	{ 633, kMazeEntryWalk, 16, 128, kFacingPositionRight, 81, 128 },
};

static const MazeDialogueLine kMaze63Lines104[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze63Actions[] = {
	MAZE_EXIT(101, 164, 106, 164, 92, 0),
	MAZE_STAIRS_EXIT(102, 164, 2),
	MAZE_EXIT(103, 71, 128, 16, 128, 3),
	MAZE_DIALOGUE(104, kMaze63Lines104, 1, 1, 1),
};

static const MazeEntry kMaze64Entries[] = {
	{ 640, kMazeEntryWalk, 214, 92, kFacingPositionFront, 214, 110 },
	{ 641, kMazeEntryWalk, 313, 128, kFacingPositionLeft, 279, 128 },
	{ 643, kMazeEntryWalk, 16, 128, kFacingPositionRight, 135, 128 },
};

static const MazeDialogueLine kMaze64Lines104[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze64Actions[] = {
	MAZE_EXIT(101, 214, 106, 214, 92, 0),
	MAZE_EXIT(102, 289, 128, 313, 128, 1),
	MAZE_EXIT(103, 125, 128, 16, 128, 3),
	MAZE_DIALOGUE(104, kMaze64Lines104, 1, 1, 1),
};

static const MazeEntry kMaze65Entries[] = {
	{ 650, kMazeEntryWalk, 105, 92, kFacingPositionFront, 105, 110 },
	{ 651, kMazeEntryWalk, 240, 128, kFacingPositionLeft, 180, 128 },
	{ 652, kMazeEntryStairs, 105, 0, 0, 0, 0 },
	{ 653, kMazeEntryWalk, 16, 127, kFacingPositionRight, 48, 127 },
};

static const MazeDialogueLine kMaze65Lines105[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze65Actions[] = {
	MAZE_EXIT(101, 105, 106, 105, 92, 0),
	MAZE_EXIT(102, 190, 128, 240, 128, 1),
	MAZE_STAIRS_EXIT(103, 105, 2),
	MAZE_EXIT(104, 38, 127, 16, 127, 3),
	MAZE_DIALOGUE(105, kMaze65Lines105, 1, 1, 1),
};

static const MazeEntry kMaze66Entries[] = {
	{ 660, kMazeEntryWalk, 164, 92, kFacingPositionFront, 164, 110 },
	{ 663, kMazeEntryWalk, 16, 128, kFacingPositionRight, 81, 128 },
};

static const MazeDialogueLine kMaze66Lines103[] = {
	{ 201, 2, 1149 },
};
static const MazeDialogueLine kMaze66Lines104[] = {
	{ 203, 1, 1150 },
};
static const MazeDialogueLine kMaze66Lines105[] = {
	{ 204, 2, 1151 },
	{ 206, 2, 1152 },
	{ 208, 1, 1153 },
};
static const MazeDialogueLine kMaze66Lines106[] = {
	{ 209, 2, 1154 },
};
static const MazeAction kMaze66Actions[] = {
	MAZE_EXIT_FIXED(101, 164, 106, 164, 92, 105, 562, -1, 0),
	MAZE_EXIT_FIXED(102, 71, 128, 16, 128, -1, 500, 70, 1),
	MAZE_DIALOGUE(103, kMaze66Lines103, 1, 1, 1),
	MAZE_DIALOGUE(104, kMaze66Lines104, 1, 1, 1),
	MAZE_DIALOGUE(105, kMaze66Lines105, 3, 3, 1),
	MAZE_DIALOGUE(106, kMaze66Lines106, 1, 1, 1),
};

static const MazeEntry kMaze67Entries[] = {
	{ 670, kMazeEntryWalk, 154, 92, kFacingPositionFront, 154, 110 },
	{ 671, kMazeEntryWalk, 298, 128, kFacingPositionLeft, 240, 128 },
};

static const MazeDialogueLine kMaze67Lines103[] = {
	{ 211, 2, 1155 },
};
static const MazeDialogueLine kMaze67Lines104[] = {
	{ 201, 2, 1149 },
};
static const MazeAction kMaze67Actions[] = {
	MAZE_EXIT_FIXED(101, 154, 106, 154, 92, -1, 142, -1, 0),
	MAZE_EXIT_FIXED(102, 248, 128, 298, 128, 85, 643, -1, 0),
	MAZE_DIALOGUE(103, kMaze67Lines103, 1, 1, 1),
	MAZE_DIALOGUE(104, kMaze67Lines104, 1, 1, 1),
};

static const MazeRoom kMazeRooms[] = {
	{ 51, DAT_Maze51, TXT_Maze51, IMG_Maze51, PAL_Maze51, MSK_Maze51, BOX_Maze51, -1, 5, kMazeFlameFirstFrame, 2,
	  { { 217, 53 }, { 84, 52 } }, { 0, 4 }, 4,
	  false, &kMazeOffsets0, 0,
	  { 128, 119, 202, true, false },
	  kMaze51Entries, 1, kMaze51Actions, 2, 0 },
	{ 52, DAT_Maze52, TXT_Maze52, IMG_Maze52, PAL_Maze52, MSK_Maze52, BOX_Maze52, -1, 5, kMazeFlameLayer1, 2,
	  { { 81, 63 }, { 37, 71 } }, { 0, 4 }, 4,
	  false, &kMazeOffsets0, 0,
	  { 128, 125, 248, true, false },
	  kMaze52Entries, 1, kMaze52Actions, 2, 0 },
	{ 53, DAT_Maze53, TXT_Maze53, IMG_Maze53, PAL_Maze53, MSK_Maze53, BOX_Maze53, -1, 8, kMazeFlameLayer1, 1,
	  { { 217, 52 } }, { 0 }, 0,
	  false, &kMazeOffsets0, 0,
	  { 143, 64, 223, false, false },
	  kMaze53Entries, 1, kMaze53Actions, 2, 0 },
	{ 54, DAT_Maze54, TXT_Maze54, IMG_Maze54, PAL_Maze54, MSK_Maze54, BOX_Maze54, -1, 13, kMazeFlameLayer1, 1,
	  { { 288, 38 } }, { 0 }, 0,
	  false, &kMazeOffsets0, 0,
	  { 128, 20, 274, true, false },
	  kMaze54Entries, 1, kMaze54Actions, 2, 0 },
	{ 55, DAT_Maze55, TXT_MazeEntrance, IMG_MazeEntrance, PAL_MazeEntrance, MSK_MazeEntrance, BOX_MazeEntrance, -1, 8, kMazeFlameFixed, 1,
	  { { 81, 52 } }, { 0 }, 0,
	  false, &kMazeOffsets1, 0,
	  { 128, 112, 248, true, false },
	  kMaze55Entries, 2, kMaze55Actions, 3, 0 },
	{ 56, DAT_Maze56, TXT_Maze56, IMG_Maze56, PAL_Maze56, MSK_Maze56, BOX_Maze56, -1, 8, kMazeFlameLayer1, 1,
	  { { 83, 52 } }, { 0 }, 0,
	  true, &kMazeOffsets1, 0,
	  { 143, 95, 249, false, false },
	  kMaze56Entries, 2, kMaze56Actions, 3, 0 },
	{ 57, DAT_Maze57, TXT_Maze57, IMG_Maze57, PAL_Maze57, MSK_Maze57, BOX_Maze57, -1, 8, kMazeFlameLayer1, 2,
	  { { 113, 13 }, { 157, 12 } }, { 0, 4 }, 0,
	  false, &kMazeOffsets1, 0,
	  { 128, 22, 283, true, false },
	  kMaze57Entries, 2, kMaze57Actions, 3, 0 },
	{ 58, DAT_Maze58, TXT_Maze58, IMG_Maze58, PAL_Maze58, MSK_Maze58, BOX_Maze58, -1, 8, kMazeFlameLayer1, 1,
	  { { 83, 53 } }, { 0 }, 0,
	  false, &kMazeOffsets1, 0,
	  { 143, 97, 248, false, false },
	  kMaze58Entries, 2, kMaze58Actions, 3, 0 },
	{ 59, DAT_Maze59, TXT_Maze59, IMG_Maze59, PAL_Maze59, MSK_Maze59, BOX_Maze59, -1, 13, kMazeFlameLayer1, 1,
	  { { 127, 22 } }, { 0 }, 0,
	  true, &kMazeOffsets2, 76,
	  { 128, 22, 304, true, false },
	  kMaze59Entries, 2, kMaze59Actions, 3, 0 },
	{ 60, DAT_Maze60, TXT_Maze60, IMG_Maze60, PAL_Maze60, MSK_Maze60, BOX_Maze60, -1, 13, kMazeFlameLayer1, 1,
	  { { 157, 13 } }, { 0 }, 0,
	  false, &kMazeOffsets2, 76,
	  { 143, -1, 299, false, false },
	  kMaze60Entries, 2, kMaze60Actions, 3, 0 },
	{ 61, DAT_Maze61, TXT_Maze61, IMG_Maze61, PAL_Maze61, MSK_Maze61, BOX_Maze61, -1, 13, kMazeFlameLayer1, 1,
	  { { 157, 12 } }, { 0 }, 0,
	  false, &kMazeOffsets3, 76,
	  { 143, 21, 291, false, false },
	  kMaze61Entries, 3, kMaze61Actions, 4, 0 },
	{ 62, DAT_Maze62, TXT_Maze62, IMG_Maze62, PAL_Maze62, MSK_Maze62, BOX_Maze62, -1, 10, kMazeFlameLayer1, 2,
	  { { 174, 23 }, { 126, 23 } }, { 0, 4 }, 4,
	  false, &kMazeOffsets3, 76,
	  { 143, -1, -1, false, false },
	  kMaze62Entries, 3, kMaze62Actions, 4, 0 },
	{ 63, DAT_Maze63, TXT_Maze63, IMG_Maze63, PAL_Maze63, MSK_Maze63, BOX_Maze63, -1, 8, kMazeFlameLayer1, 1,
	  { { 217, 52 } }, { 0 }, 0,
	  true, &kMazeOffsets3, 76,
	  { 143, 71, 222, false, false },
	  kMaze63Entries, 3, kMaze63Actions, 4, 0 },
	{ 64, DAT_Maze64, TXT_Maze64, IMG_Maze64, PAL_Maze64, MSK_Maze64, BOX_Maze64, -1, 13, kMazeFlameNone, 0,
	  {  }, {  }, 0,
	  false, &kMazeOffsets3, 76,
	  { 128, 125, 289, true, false },
	  kMaze64Entries, 3, kMaze64Actions, 4, 0 },
	{ 65, DAT_Maze65, TXT_Maze65, IMG_Maze65, PAL_Maze65, MSK_Maze65, BOX_Maze65, -1, 12, kMazeFlameNone, 0,
	  {  }, {  }, 0,
	  false, &kMazeOffsets4, 76,
	  { 143, 22, 208, false, false },
	  kMaze65Entries, 4, kMaze65Actions, 5, 0 },
	{ 66, DAT_Maze66, TXT_Maze66, IMG_Maze66, PAL_Maze66, MSK_Maze66, BOX_Maze66, 7, 8, kMazeFlameLayer1, 1,
	  { { 217, 52 } }, { 0 }, 0,
	  false, &kMazeOffsets3, 76,
	  { 143, 71, 222, false, false },
	  kMaze66Entries, 2, kMaze66Actions, 6, " esqueleto" },
	{ 67, DAT_MazeEntrance, TXT_MazeEntrance, IMG_MazeEntrance, PAL_MazeEntrance, MSK_MazeEntrance, BOX_MazeEntrance, 5, 8, kMazeFlameFixed, 1,
	  { { 81, 52 } }, { 0 }, 0,
	  false, &kMazeOffsets1, 0,
	  { 128, 112, 248, true, false },
	  kMaze67Entries, 2, kMaze67Actions, 4, 0 }
};

const MazeRoom *IgorEngine::getMazeRoom(int part) {
	for (int i = 0; i < ARRAYSIZE(kMazeRooms); ++i) {
		if (kMazeRooms[i].part == part) {
			return &kMazeRooms[i];
		}
	}
	return 0;
}

} // End of namespace Igor
